# environment.yaml
name: lunch-menu-app
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - flask
  - flask-socketio
  - flask-sqlalchemy
  - flask-limiter
  - beautifulsoup4
  - requests
  - selenium
  - apscheduler
  - python-socketio
  - eventlet
  - lxml
  - pypdf2
  - python-dotenv
  - redis-py
  - pip
  - gunicorn       # For production deployment
  - eventlet
  
  - pip:
    - pdfplumber
    - webdriver-manager
    - flask-limiter
    - flask-talisman
    - bleach
    - validators
