# environment.yaml (Revised for Stability)
name: lunch-menu-app
channels:
  - conda-forge
  - defaults
dependencies:
  # 1. Use a stable, widely-supported Python version. This is the key fix.
  - python=3.11

  # 2. Let Conda resolve the latest compatible versions of these packages.
  #    This is more robust than pinning every version.
  - flask
  - flask-socketio
  - flask-sqlalchemy
  - beautifulsoup4
  - requests
  - selenium
  - apscheduler
  - python-socketio
  - eventlet
  - lxml
  - pypdf2
  - python-dotenv
  - pip

  # 3. Use pip for packages not available on Conda.
  - pip:
    - pdfplumber
    - webdriver-manager
